name: snapshot
on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
jobs:
  publish-snapshot:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - env:
          CENTRAL_RELEASE_MAVEN_REPOSITORY_URL: ${{ secrets.CENTRAL_RELEASE_MAVEN_REPOSITORY_URL }}
          CENTRAL_MAVEN_REPOSITORY_USERNAME: ${{ secrets.CENTRAL_MAVEN_REPOSITORY_USERNAME }}
          CENTRAL_MAVEN_REPOSITORY_PASSWORD: ${{ secrets.CENTRAL_MAVEN_REPOSITORY_PASSWORD }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew raygun-spring-boot-starter:publishMavenPublicationToCentralSnapshotRepository
